language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
 - pytest --cov=app
services:
  - postgresql 
before_script:
  - psql -c "CREATE DATABASE politico ;" -U postgres
  
after_success:
- coveralls