language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
 - pytest --cov=app
before_script:
  - psql -c "CREATE DATABASE politico ;" -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'oscarcom5';" -U postgres 
after_success:
- coveralls