language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev" 

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
before_script:
    - export FLASK_APP=run.py
    - export FLASK_DEBUG=1
    - export FLASK_ENV=development

